### PR TITLE
Upgrade Node to >= 6 and asar to ^1.0.0

### PR DESCRIPTION
**Pull request by malept**
This is in response to the changes in https://github.com/electron/asar/pull/165. This module only uses `extractFile`, so it should be fine with zero changes other than to `package.json`.

### CODE REVIEW

**Comment by carterbs** [comment]
@MarshallOfSound wondering if this will be merged in the coming weeks. Would be great to have our audit return 0 vulnerabilities.

**Comment by malept** [comment]
This is *technically* a vulnerability that can be ignored for this module, as `electron-winstaller` doesn't use any of the functionality provided by the transitive dependency in `asar`.

**Comment by carterbs** [comment]
> This is _technically_ a vulnerability that can be ignored for this module, as `electron-winstaller` doesn't use any of the functionality provided by the transitive dependency in `asar`.

Hey Mark. Thanks for the note. I could possibly sell that. I would so much rather not have to. :-) Thank you for submitting this PR, and for getting an update for packager pushed out so quickly.

**Comment by malept** [comment]
Ugh. This module requires Node 4, and `asar` requires Node 6. I guess we're major version bumping. Might as well do some cleanup while we're doing that.

**Pull request merged**
