### PR TITLE
feat!: update to Squirrel 2.0.1

### PR DESCRIPTION
**Pull request by dennisameling**
Follow-up on https://github.com/electron/windows-installer/pull/354 which was created by @anaisbetts. Squirrel 2.0.1 has been released in the meantime which fixes some issues. This PR includes the 2.0.1 binaries. 

From the original PR:

> See https://github.com/Squirrel/Squirrel.Windows/releases/tag/2.0.0 for what's new, the tl;dr; for Electron applications is:
> - ARM64 Windows installers can now be built
> - Improvements to MSI installers
> - Log files are More Betterer

### CODE REVIEW

**Comment by dennisameling** [comment]
Just updated this PR so that it not only enables cross-compiling for Windows arm64 on a x64 host, but also running natively on arm64 🚀 this PR automatically selects the right `7z.exe` and `7z.dll` based on host OS architecture.

If you want to easily test this PR, you can do so by installing `npm install --save-dev electron-winstaller-test-dennis`.

Just tested this PR with GitHub Desktop on my arm64 Surface Pro X, can confirm the packages are built correctly:

image

Installation also works as expected:

image

image

After installation, I have a working instance of GitHub Desktop:

image

**Comment by dennisameling** [comment]
@malept sorry to bother you, but do you think this PR likely to be reviewed anytime soon? It's currently blocking https://github.com/desktop/desktop/pull/9691. Please let me know if I can be of any further help here. Thanks in advance 🚀

**Review by gottogon — COMMENTED** [review]
Good choice

**Comment by niik** [comment]
@anaisbetts :wave: GitHub Desktop is investigating upgrading to Squirrel 2.0.1, just wanted to check that the issues you mentioned in https://github.com/electron/windows-installer/pull/354#issuecomment-682463137 about 2.0.0 have all been adequately resolved now?

> Let's hold off on this, we found a few issues I want to investigate

**Comment by dennisameling** [comment]
Closing in favor of https://github.com/electron/windows-installer/pull/369

**Pull request closed without merging**
