### PR TITLE
Allow loadingGif to be disabled.

### PR DESCRIPTION
**Pull request by BobBuehler**
I'm open to alternative ways to expose this functionality but this seemed straightforward enough.

### CODE REVIEW

**Comment by develar** [comment]
Squirrel.Windows supports `--silent` flag, and it seems is a right way to disable loading gif.

**Comment by BobBuehler** [comment]
I agree with @develar.

**Comment by kjantzer** [comment]
@develar, how would one go about using the `--silent` flag with windows-installer?

**Comment by develar** [comment]
@kjantzer It is runtime flag (passed to setup exe).

**Pull request closed without merging**
