### PR TITLE
feat!: Update to Squirrel.Windows 2.0.1

### PR DESCRIPTION
**Pull request by anaisbetts**
This is @dennisameling's great PR #361 but with the released Squirrel.Windows 2.0.1 binaries. :shipit:!  See #354 for the details of what's new

### CODE REVIEW

**Comment by dennisameling** [comment]
Can confirm this works as expected on Windows arm64 🚀 The installer itself I also created on an `arm64` device thanks to the 7-Zip `arm64` binaries from this PR.

Installers are created correctly:

image

The program is installed correctly as well:

image

**Review by malept — COMMENTED** [review]
This seems fine to me but I'd like @MarshallOfSound to take a look for a second opinion.

**Comment by anaisbetts** [comment]
@malept I think he had a look at the previous PR and 👍d it, this one has no changes other than the updated binaries

**Comment by tommyvct** [comment]
Now it's been for 2 weeks, still nothing?

**Comment by dennisameling** [comment]
Hi @MarshallOfSound, we'd be super grateful if you could review this PR. It's the final blocker for GitHub Desktop on ARM64: https://github.com/desktop/desktop/pull/9691. Thanks in advance! 😊

**Review by MarshallOfSound — APPROVED** [review]

**Pull request merged**
