### PR TITLE
Version bump to Squirrel.Windows 1.4.2

### PR DESCRIPTION
**Pull request by paulcbetts**
This is a patch release to fix https://github.com/Squirrel/Squirrel.Windows/issues/765

### CODE REVIEW

**Comment by paulcbetts** [comment]
@kevinsawicki can you merge this asap? People are getting trolled by the current release

**Comment by MarshallOfSound** [comment]
Yeah I got trolled bad. :sad:

**Comment by kevinsawicki** [comment]
Published in 2.3.3, sorry for the delay.

**Comment by paulcbetts** [comment]
Thanks

**Pull request merged**
