### PR TITLE
feat: update nuget to v6.10.1

### PR DESCRIPTION
**Pull request by beyondkmp**
The current version of NuGet causes the CPU usage to be nearly 100% and the memory usage to be very high, almost 2GB during packaging.

```
Mem:           1.8Gi       1.7Gi        65Mi       2.0Mi       212Mi       114Mi
Swap:          2.0Gi        39Mi       2.0Gi
```

The latest version of NuGet only uses about 600MB of memory.
```
               total        used        free      shared  buff/cache   available
Mem:           1.8Gi       594Mi        61Mi       2.1Mi       1.3Gi       1.2Gi
Swap:             0B          0B          0B
```

The nuget downloads from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
md5:  6b260d67fc4f18048347ae3c0d8e59bf

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
I don't have an opinion on the update and will leave that to review by a windows-installer maintainer, but since this is an .exe contribution from someone who's not  an Electron maintainer --

FWIW this appears to be a legit copy.

Using `cmp`, I did a byte-for-byte comparison of the `nuget.exe` in commit 281aa1495cb5c0d4ae6f8ed288ffa7b4e8d9c57a of this PR to a copy I downloaded manually from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe. `cmp` says they are identical. :+1:

**Comment by beyondkmp** [comment]
@ckerr Could you help merge it?

**Comment by ckerr** [comment]
@beyondkmp I'd like at least one other person from @electron/wg-ecosystem to TAL too; but yeah, it's been two weeks. If nobody else reviews I'm :+1: on this PR

**Review by ckerr — APPROVED** [review]

**Comment by dsanders11** [comment]
@ckerr, I believe the decision during the last Ecosystem WG meeting was to merge #526 to provide the escape hatch mechanism, but otherwise close these individual upgrades to NuGet and 7Zip, see Felix's comment here: https://github.com/electron/windows-installer/pull/526#pullrequestreview-2195217425.

Unfortunately this project is lightly maintained at the moment and we don't feel confident in updating these without more due diligence than we currently have bandwidth for. As such I'm going to close this PR, but we will hopefully revisit it in the future.

**Comment by Bug-Reaper** [comment]
> @ckerr, I believe the decision during the last Ecosystem WG meeting was to merge #526 to provide the escape hatch mechanism, but otherwise close these individual upgrades to NuGet and 7Zip, see Felix's comment here: [#526 (review)](https://github.com/electron/windows-installer/pull/526#pullrequestreview-2195217425).
> 
> Unfortunately this project is lightly maintained at the moment and we don't feel confident in updating these without more due diligence than we currently have bandwidth for. As such I'm going to close this PR, but we will hopefully revisit it in the future.

@dsanders11 

Some insight to bring up at your next discussion. Updating NuGet also fixes a variety of errors too  -- see discussion on PR https://github.com/electron/windows-installer/pull/495. These aren't particularly easy issues to debug and I have doubts that even intermediate programmers will find and use the undocumented escape hatch.

I can only imagine using a 10yr old binary is going to cause even more bugs and issues for this under-staffed effort in the future anyways.

Perhaps worth re-consideration, I'm happy to help with the effort where I can.

**Pull request closed without merging**
