### PR TITLE
feat!: update to Squirrel 2.0

### PR DESCRIPTION
**Pull request by anaisbetts**
See https://github.com/Squirrel/Squirrel.Windows/releases/tag/2.0.0 for what's new, the tl;dr; for Electron applications is:

* ARM64 Windows installers can now be built
* Improvements to MSI installers
* Log files are More Betterer

### CODE REVIEW

**Comment by malept** [comment]
@anaisbetts do you think this warrants a major or minor version bump?

**Comment by anaisbetts** [comment]
For us it was a major version bump, for Electron apps you could argue it's minor but just for paranoia's sake it'd be better to be major

**Comment by anaisbetts** [comment]
Let's hold off on this, we found a few issues I want to investigate

**Comment by dennisameling** [comment]
@anaisbetts anything I can do to help here? https://github.com/Squirrel/Squirrel.Windows/pull/1655 is merged, would that be enough to release a 2.0.1 version so that `electron/windows-installer` can start using Squirrel V2, or are there any other blockers? Thanks in advance 🚀

**Pull request closed without merging**
