### PR TITLE
Upgrade asar to drop dependency on deprecated graceful-fs@3

### LINKED ISSUE #83: Update asar dep to ~0.11.0
To fix the following install warning:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

### PR DESCRIPTION
**Pull request by fasterthanlime**
Cf. #83 for report.

(tilde would work just as well as caret, might make sense since asar is in 0.x — alternatively, asar could be updated to [respect semver](https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-publishers))

### CODE REVIEW

**Comment by feross** [comment]
LGTM

**Comment by kevinsawicki** [comment]
Thanks 👍

**Comment by fasterthanlime** [comment]
Wouldn't it be good to make a new point release so grunt-electron-installer picks it up?

**Comment by kevinsawicki** [comment]
> Wouldn't it be good to make a new point release so grunt-electron-installer picks it up?

Thanks, published in `2.3.1`

**Pull request merged**
