### PR TITLE
WIP: Use ava instead of chai and mocha.

### PR DESCRIPTION
**Pull request by havenchyk**
WIP: it's unclear for me, why [this line](https://github.com/electron/windows-installer/compare/master...havenchyk:ava?diff=unified&expand=1&name=ava#diff-d005ed88857d6d584341a0fb95df9ac5R19) is needed. @paulcbetts could you please clarify it?

### CODE REVIEW

**Comment by develar** [comment]
@havenchyk "this line" It is why AVA is awesome :) You don't need to configure timeouts — default is reasonable (well, it seems AVA can hangs also, but I like AVA approach —and its more suitable for tools like ours).

**Comment by paulcbetts** [comment]
What's the benefit to using ava over chai/mocha?

**Comment by lukeapage** [comment]
Its hard to see the changes since you've added to your jetpacks-> fs extra branch.

I like the look of ava, particularly for this project where the richer describe/it/expect is not important (I'd favour mocha/chai if this was a front-end web app for instance, but it isn't so it doesn't add much), but I don't see the point of changing  - 
1. mocha/chai is more popular
2. mocha is used in electron

**Comment by develar** [comment]
> richer describe/it/expect is not important

AVA supports [any assertion framework](https://github.com/sindresorhus/ava#custom-assertions). E.g. in the electron-builder we use shouldjs.

> What's the benefit to using ava over chai/mocha?

"runs your tests concurrently, which is especially beneficial for IO heavy tests". It is why we use AVA in electron-builder tests. Tests should be executed quickly, otherwise it is not useful and developer will not use it.

Well, windows-installer doesn't yet have relatively large test suite as electron-builder, but anyway.

AVA allows me to use full potential of my 4 GHz Intel Core i7 and SSD :)

**Comment by havenchyk** [comment]
Closed this one. Continue with #57.

**Pull request closed without merging**
